stages:
  - setup
  - compile
  - test
  - deploy

variables:
  plugin: AttributesExtension
  engine_version: 23

cache:
  paths:
    - Build/

setup python:
  stage: setup
  script:
    - python -m pip install ue4cli

build plugin:
  stage: compile
  script:
    - cmd.exe /c E:\Piperift\GitlabRunner\Lib\BuildPlugin.bat

unit test:
  stage: test
  script:
    - echo No tests implemented

upload:
  stage: deploy
  script:
    - cmd.exe /c E:\Piperift\GitlabRunner\Lib\CompressPlugin.bat
    - cmd.exe /c E:\Piperift\GitlabRunner\Lib\Upload.bat
